// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/group_repo/group.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/group_repo/group.go -destination=internal/repository/group_repo/mock_group_repo/group.go -package=mock_group_repo
//

// Package mock_group_repo is a generated GoMock package.
package mock_group_repo

import (
	context "context"
	reflect "reflect"

	group_entity "github.com/opskat/opskat/internal/model/entity/group_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupRepo is a mock of GroupRepo interface.
type MockGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepoMockRecorder
	isgomock struct{}
}

// MockGroupRepoMockRecorder is the mock recorder for MockGroupRepo.
type MockGroupRepoMockRecorder struct {
	mock *MockGroupRepo
}

// NewMockGroupRepo creates a new mock instance.
func NewMockGroupRepo(ctrl *gomock.Controller) *MockGroupRepo {
	mock := &MockGroupRepo{ctrl: ctrl}
	mock.recorder = &MockGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepo) EXPECT() *MockGroupRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupRepo) Create(ctx context.Context, group *group_entity.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupRepoMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupRepo)(nil).Create), ctx, group)
}

// Delete mocks base method.
func (m *MockGroupRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockGroupRepo) Find(ctx context.Context, id int64) (*group_entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*group_entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockGroupRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockGroupRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockGroupRepo) List(ctx context.Context) ([]*group_entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*group_entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupRepo)(nil).List), ctx)
}

// ReparentChildren mocks base method.
func (m *MockGroupRepo) ReparentChildren(ctx context.Context, oldParentID, newParentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReparentChildren", ctx, oldParentID, newParentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReparentChildren indicates an expected call of ReparentChildren.
func (mr *MockGroupRepoMockRecorder) ReparentChildren(ctx, oldParentID, newParentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReparentChildren", reflect.TypeOf((*MockGroupRepo)(nil).ReparentChildren), ctx, oldParentID, newParentID)
}

// Update mocks base method.
func (m *MockGroupRepo) Update(ctx context.Context, group *group_entity.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupRepoMockRecorder) Update(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupRepo)(nil).Update), ctx, group)
}

// UpdateSortOrder mocks base method.
func (m *MockGroupRepo) UpdateSortOrder(ctx context.Context, id int64, sortOrder int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSortOrder", ctx, id, sortOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSortOrder indicates an expected call of UpdateSortOrder.
func (mr *MockGroupRepoMockRecorder) UpdateSortOrder(ctx, id, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSortOrder", reflect.TypeOf((*MockGroupRepo)(nil).UpdateSortOrder), ctx, id, sortOrder)
}
