// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/conversation_repo/conversation.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/conversation_repo/conversation.go -destination=internal/repository/conversation_repo/mock_conversation_repo/conversation.go -package=mock_conversation_repo
//

// Package mock_conversation_repo is a generated GoMock package.
package mock_conversation_repo

import (
	context "context"
	reflect "reflect"

	conversation_entity "github.com/opskat/opskat/internal/model/entity/conversation_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationRepo is a mock of ConversationRepo interface.
type MockConversationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockConversationRepoMockRecorder
	isgomock struct{}
}

// MockConversationRepoMockRecorder is the mock recorder for MockConversationRepo.
type MockConversationRepoMockRecorder struct {
	mock *MockConversationRepo
}

// NewMockConversationRepo creates a new mock instance.
func NewMockConversationRepo(ctrl *gomock.Controller) *MockConversationRepo {
	mock := &MockConversationRepo{ctrl: ctrl}
	mock.recorder = &MockConversationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationRepo) EXPECT() *MockConversationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConversationRepo) Create(ctx context.Context, conv *conversation_entity.Conversation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, conv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConversationRepoMockRecorder) Create(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConversationRepo)(nil).Create), ctx, conv)
}

// CreateMessages mocks base method.
func (m *MockConversationRepo) CreateMessages(ctx context.Context, msgs []*conversation_entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessages", ctx, msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessages indicates an expected call of CreateMessages.
func (mr *MockConversationRepoMockRecorder) CreateMessages(ctx, msgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessages", reflect.TypeOf((*MockConversationRepo)(nil).CreateMessages), ctx, msgs)
}

// Delete mocks base method.
func (m *MockConversationRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConversationRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConversationRepo)(nil).Delete), ctx, id)
}

// DeleteMessages mocks base method.
func (m *MockConversationRepo) DeleteMessages(ctx context.Context, conversationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessages", ctx, conversationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessages indicates an expected call of DeleteMessages.
func (mr *MockConversationRepoMockRecorder) DeleteMessages(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessages", reflect.TypeOf((*MockConversationRepo)(nil).DeleteMessages), ctx, conversationID)
}

// Find mocks base method.
func (m *MockConversationRepo) Find(ctx context.Context, id int64) (*conversation_entity.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*conversation_entity.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockConversationRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockConversationRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockConversationRepo) List(ctx context.Context) ([]*conversation_entity.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*conversation_entity.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConversationRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConversationRepo)(nil).List), ctx)
}

// ListMessages mocks base method.
func (m *MockConversationRepo) ListMessages(ctx context.Context, conversationID int64) ([]*conversation_entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, conversationID)
	ret0, _ := ret[0].([]*conversation_entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockConversationRepoMockRecorder) ListMessages(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockConversationRepo)(nil).ListMessages), ctx, conversationID)
}

// Update mocks base method.
func (m *MockConversationRepo) Update(ctx context.Context, conv *conversation_entity.Conversation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConversationRepoMockRecorder) Update(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConversationRepo)(nil).Update), ctx, conv)
}
