// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/asset_repo/asset.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/asset_repo/asset.go -destination=internal/repository/asset_repo/mock_asset_repo/asset.go -package=mock_asset_repo
//

// Package mock_asset_repo is a generated GoMock package.
package mock_asset_repo

import (
	context "context"
	asset_entity "github.com/opskat/opskat/internal/model/entity/asset_entity"
	asset_repo "github.com/opskat/opskat/internal/repository/asset_repo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAssetRepo is a mock of AssetRepo interface.
type MockAssetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAssetRepoMockRecorder
	isgomock struct{}
}

// MockAssetRepoMockRecorder is the mock recorder for MockAssetRepo.
type MockAssetRepoMockRecorder struct {
	mock *MockAssetRepo
}

// NewMockAssetRepo creates a new mock instance.
func NewMockAssetRepo(ctrl *gomock.Controller) *MockAssetRepo {
	mock := &MockAssetRepo{ctrl: ctrl}
	mock.recorder = &MockAssetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetRepo) EXPECT() *MockAssetRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAssetRepo) Create(ctx context.Context, asset *asset_entity.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAssetRepoMockRecorder) Create(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAssetRepo)(nil).Create), ctx, asset)
}

// Delete mocks base method.
func (m *MockAssetRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAssetRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAssetRepo)(nil).Delete), ctx, id)
}

// DeleteByGroupID mocks base method.
func (m *MockAssetRepo) DeleteByGroupID(ctx context.Context, groupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByGroupID", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByGroupID indicates an expected call of DeleteByGroupID.
func (mr *MockAssetRepoMockRecorder) DeleteByGroupID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByGroupID", reflect.TypeOf((*MockAssetRepo)(nil).DeleteByGroupID), ctx, groupID)
}

// Find mocks base method.
func (m *MockAssetRepo) Find(ctx context.Context, id int64) (*asset_entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*asset_entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAssetRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAssetRepo)(nil).Find), ctx, id)
}

// FindByCredentialID mocks base method.
func (m *MockAssetRepo) FindByCredentialID(ctx context.Context, credentialID int64) ([]*asset_entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCredentialID", ctx, credentialID)
	ret0, _ := ret[0].([]*asset_entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCredentialID indicates an expected call of FindByCredentialID.
func (mr *MockAssetRepoMockRecorder) FindByCredentialID(ctx, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCredentialID", reflect.TypeOf((*MockAssetRepo)(nil).FindByCredentialID), ctx, credentialID)
}

// List mocks base method.
func (m *MockAssetRepo) List(ctx context.Context, opts asset_repo.ListOptions) ([]*asset_entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*asset_entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAssetRepoMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAssetRepo)(nil).List), ctx, opts)
}

// MoveToGroup mocks base method.
func (m *MockAssetRepo) MoveToGroup(ctx context.Context, fromGroupID, toGroupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToGroup", ctx, fromGroupID, toGroupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveToGroup indicates an expected call of MoveToGroup.
func (mr *MockAssetRepoMockRecorder) MoveToGroup(ctx, fromGroupID, toGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToGroup", reflect.TypeOf((*MockAssetRepo)(nil).MoveToGroup), ctx, fromGroupID, toGroupID)
}

// Update mocks base method.
func (m *MockAssetRepo) Update(ctx context.Context, asset *asset_entity.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAssetRepoMockRecorder) Update(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAssetRepo)(nil).Update), ctx, asset)
}

// UpdateSortOrder mocks base method.
func (m *MockAssetRepo) UpdateSortOrder(ctx context.Context, id int64, sortOrder int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSortOrder", ctx, id, sortOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSortOrder indicates an expected call of UpdateSortOrder.
func (mr *MockAssetRepoMockRecorder) UpdateSortOrder(ctx, id, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSortOrder", reflect.TypeOf((*MockAssetRepo)(nil).UpdateSortOrder), ctx, id, sortOrder)
}

// CountByTypes mocks base method.
func (m *MockAssetRepo) CountByTypes(ctx context.Context, types []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTypes", ctx, types)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTypes indicates an expected call of CountByTypes.
func (mr *MockAssetRepoMockRecorder) CountByTypes(ctx, types any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTypes", reflect.TypeOf((*MockAssetRepo)(nil).CountByTypes), ctx, types)
}
