// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/extension_state_repo/extension_state.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/extension_state_repo/extension_state.go -destination=internal/repository/extension_state_repo/mock_extension_state_repo/extension_state.go -package=mock_extension_state_repo
//

// Package mock_extension_state_repo is a generated GoMock package.
package mock_extension_state_repo

import (
	context "context"
	reflect "reflect"

	extension_state_entity "github.com/opskat/opskat/internal/model/entity/extension_state_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockExtensionStateRepo is a mock of ExtensionStateRepo interface.
type MockExtensionStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionStateRepoMockRecorder
	isgomock struct{}
}

// MockExtensionStateRepoMockRecorder is the mock recorder for MockExtensionStateRepo.
type MockExtensionStateRepoMockRecorder struct {
	mock *MockExtensionStateRepo
}

// NewMockExtensionStateRepo creates a new mock instance.
func NewMockExtensionStateRepo(ctrl *gomock.Controller) *MockExtensionStateRepo {
	mock := &MockExtensionStateRepo{ctrl: ctrl}
	mock.recorder = &MockExtensionStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionStateRepo) EXPECT() *MockExtensionStateRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExtensionStateRepo) Create(ctx context.Context, state *extension_state_entity.ExtensionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExtensionStateRepoMockRecorder) Create(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExtensionStateRepo)(nil).Create), ctx, state)
}

// Delete mocks base method.
func (m *MockExtensionStateRepo) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExtensionStateRepoMockRecorder) Delete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExtensionStateRepo)(nil).Delete), ctx, name)
}

// Find mocks base method.
func (m *MockExtensionStateRepo) Find(ctx context.Context, name string) (*extension_state_entity.ExtensionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, name)
	ret0, _ := ret[0].(*extension_state_entity.ExtensionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockExtensionStateRepoMockRecorder) Find(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockExtensionStateRepo)(nil).Find), ctx, name)
}

// FindAll mocks base method.
func (m *MockExtensionStateRepo) FindAll(ctx context.Context) ([]*extension_state_entity.ExtensionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*extension_state_entity.ExtensionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockExtensionStateRepoMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockExtensionStateRepo)(nil).FindAll), ctx)
}

// Update mocks base method.
func (m *MockExtensionStateRepo) Update(ctx context.Context, state *extension_state_entity.ExtensionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExtensionStateRepoMockRecorder) Update(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExtensionStateRepo)(nil).Update), ctx, state)
}
