// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/extension_data_repo/extension_data.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/extension_data_repo/extension_data.go -destination=internal/repository/extension_data_repo/mock_extension_data_repo/extension_data.go -package=mock_extension_data_repo
//

// Package mock_extension_data_repo is a generated GoMock package.
package mock_extension_data_repo

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExtensionDataRepo is a mock of ExtensionDataRepo interface.
type MockExtensionDataRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionDataRepoMockRecorder
	isgomock struct{}
}

// MockExtensionDataRepoMockRecorder is the mock recorder for MockExtensionDataRepo.
type MockExtensionDataRepoMockRecorder struct {
	mock *MockExtensionDataRepo
}

// NewMockExtensionDataRepo creates a new mock instance.
func NewMockExtensionDataRepo(ctrl *gomock.Controller) *MockExtensionDataRepo {
	mock := &MockExtensionDataRepo{ctrl: ctrl}
	mock.recorder = &MockExtensionDataRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionDataRepo) EXPECT() *MockExtensionDataRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockExtensionDataRepo) Delete(ctx context.Context, extName, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, extName, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExtensionDataRepoMockRecorder) Delete(ctx, extName, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExtensionDataRepo)(nil).Delete), ctx, extName, key)
}

// DeleteAll mocks base method.
func (m *MockExtensionDataRepo) DeleteAll(ctx context.Context, extName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, extName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockExtensionDataRepoMockRecorder) DeleteAll(ctx, extName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockExtensionDataRepo)(nil).DeleteAll), ctx, extName)
}

// Get mocks base method.
func (m *MockExtensionDataRepo) Get(ctx context.Context, extName, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, extName, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExtensionDataRepoMockRecorder) Get(ctx, extName, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExtensionDataRepo)(nil).Get), ctx, extName, key)
}

// Set mocks base method.
func (m *MockExtensionDataRepo) Set(ctx context.Context, extName, key string, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, extName, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockExtensionDataRepoMockRecorder) Set(ctx, extName, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockExtensionDataRepo)(nil).Set), ctx, extName, key, value)
}
