// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/policy_group_repo/policy_group.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/policy_group_repo/policy_group.go -destination=internal/repository/policy_group_repo/mock_policy_group_repo/policy_group.go -package=mock_policy_group_repo
//

// Package mock_policy_group_repo is a generated GoMock package.
package mock_policy_group_repo

import (
	context "context"
	reflect "reflect"

	policy_group_entity "github.com/opskat/opskat/internal/model/entity/policy_group_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyGroupRepo is a mock of PolicyGroupRepo interface.
type MockPolicyGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyGroupRepoMockRecorder
	isgomock struct{}
}

// MockPolicyGroupRepoMockRecorder is the mock recorder for MockPolicyGroupRepo.
type MockPolicyGroupRepoMockRecorder struct {
	mock *MockPolicyGroupRepo
}

// NewMockPolicyGroupRepo creates a new mock instance.
func NewMockPolicyGroupRepo(ctrl *gomock.Controller) *MockPolicyGroupRepo {
	mock := &MockPolicyGroupRepo{ctrl: ctrl}
	mock.recorder = &MockPolicyGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyGroupRepo) EXPECT() *MockPolicyGroupRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPolicyGroupRepo) Create(ctx context.Context, pg *policy_group_entity.PolicyGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPolicyGroupRepoMockRecorder) Create(ctx, pg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPolicyGroupRepo)(nil).Create), ctx, pg)
}

// Delete mocks base method.
func (m *MockPolicyGroupRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPolicyGroupRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPolicyGroupRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockPolicyGroupRepo) Find(ctx context.Context, id int64) (*policy_group_entity.PolicyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*policy_group_entity.PolicyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPolicyGroupRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPolicyGroupRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockPolicyGroupRepo) List(ctx context.Context) ([]*policy_group_entity.PolicyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*policy_group_entity.PolicyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPolicyGroupRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPolicyGroupRepo)(nil).List), ctx)
}

// ListByIDs mocks base method.
func (m *MockPolicyGroupRepo) ListByIDs(ctx context.Context, ids []int64) ([]*policy_group_entity.PolicyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]*policy_group_entity.PolicyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockPolicyGroupRepoMockRecorder) ListByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockPolicyGroupRepo)(nil).ListByIDs), ctx, ids)
}

// ListByType mocks base method.
func (m *MockPolicyGroupRepo) ListByType(ctx context.Context, policyType string) ([]*policy_group_entity.PolicyGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByType", ctx, policyType)
	ret0, _ := ret[0].([]*policy_group_entity.PolicyGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByType indicates an expected call of ListByType.
func (mr *MockPolicyGroupRepoMockRecorder) ListByType(ctx, policyType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByType", reflect.TypeOf((*MockPolicyGroupRepo)(nil).ListByType), ctx, policyType)
}

// Update mocks base method.
func (m *MockPolicyGroupRepo) Update(ctx context.Context, pg *policy_group_entity.PolicyGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPolicyGroupRepoMockRecorder) Update(ctx, pg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPolicyGroupRepo)(nil).Update), ctx, pg)
}
