// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update_svc} from '../models';
import {app} from '../models';
import {policy_group_entity} from '../models';
import {asset_entity} from '../models';
import {conversation_entity} from '../models';
import {forward_entity} from '../models';
import {group_entity} from '../models';
import {credential_entity} from '../models';
import {backup_svc} from '../models';
import {extension_svc} from '../models';
import {extension} from '../models';
import {sshpool} from '../models';
import {status} from '../models';
import {import_svc} from '../models';
import {audit_repo} from '../models';
import {ai} from '../models';
import {sftp_svc} from '../models';

export function CallExtensionAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CallExtensionTool(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CancelGitHubAuth():Promise<void>;

export function CancelSSHConnect(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<update_svc.UpdateInfo>;

export function Cleanup():Promise<void>;

export function ClearGitHubToken():Promise<void>;

export function ConnectSSH(arg1:app.SSHConnectRequest):Promise<string>;

export function ConnectSSHAsync(arg1:app.SSHConnectRequest):Promise<string>;

export function CopyPolicyGroup(arg1:string,arg2:string):Promise<policy_group_entity.PolicyGroup>;

export function CreateAIProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<app.AIProviderInfo>;

export function CreateAsset(arg1:asset_entity.Asset):Promise<void>;

export function CreateConversation():Promise<conversation_entity.Conversation>;

export function CreateForwardConfig(arg1:string,arg2:number,arg3:Array<forward_entity.ForwardRule>):Promise<forward_entity.ForwardConfig>;

export function CreateGroup(arg1:group_entity.Group):Promise<void>;

export function CreatePasswordCredential(arg1:string,arg2:string,arg3:string,arg4:string):Promise<credential_entity.Credential>;

export function CreatePolicyGroup(arg1:policy_group_entity.PolicyGroup):Promise<policy_group_entity.PolicyGroup>;

export function DeleteAIProvider(arg1:number):Promise<void>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeleteCredential(arg1:number):Promise<void>;

export function DeleteForwardConfig(arg1:number):Promise<void>;

export function DeleteGroup(arg1:number,arg2:boolean):Promise<void>;

export function DeletePolicyGroup(arg1:string):Promise<void>;

export function DetectOpsctl():Promise<app.OpsctlInfo>;

export function DetectSkills():Promise<Array<app.SkillTarget>>;

export function DisableExtension(arg1:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:boolean):Promise<void>;

export function EnableExtension(arg1:string):Promise<void>;

export function EncryptPassword(arg1:string):Promise<string>;

export function ExecuteImportFile(arg1:string,arg2:string,arg3:backup_svc.ImportOptions):Promise<backup_svc.ImportResult>;

export function ExecuteRedis(arg1:number,arg2:string,arg3:number):Promise<string>;

export function ExecuteRedisArgs(arg1:number,arg2:Array<string>,arg3:number):Promise<string>;

export function ExecuteSQL(arg1:number,arg2:string,arg3:string):Promise<string>;

export function ExportData():Promise<string>;

export function ExportToFile(arg1:string,arg2:backup_svc.ExportOptions):Promise<void>;

export function ExportToGist(arg1:string,arg2:string,arg3:string,arg4:backup_svc.ExportOptions):Promise<backup_svc.GistInfo>;

export function FetchAIModels(arg1:string,arg2:string,arg3:string):Promise<Array<app.AIModelInfo>>;

export function GenerateSSHKey(arg1:string,arg2:string,arg3:string,arg4:number):Promise<credential_entity.Credential>;

export function GetActiveAIProvider():Promise<app.AIProviderInfo>;

export function GetAppVersion():Promise<string>;

export function GetAsset(arg1:number):Promise<asset_entity.Asset>;

export function GetAssetPassword(arg1:number):Promise<string>;

export function GetAvailableAssetTypes():Promise<Array<app.AssetTypeInfo>>;

export function GetAvailableMirrors():Promise<Array<update_svc.MirrorInfo>>;

export function GetCredentialPublicKey(arg1:number):Promise<string>;

export function GetCredentialUsage(arg1:number):Promise<Array<string>>;

export function GetCurrentConversationID():Promise<number>;

export function GetDataDir():Promise<string>;

export function GetDecryptedExtensionConfig(arg1:number,arg2:string):Promise<string>;

export function GetDefaultPolicy(arg1:string):Promise<string>;

export function GetDownloadMirror():Promise<string>;

export function GetExtensionDetail(arg1:string):Promise<extension_svc.ExtensionInfo>;

export function GetExtensionManifest(arg1:string):Promise<extension.Manifest>;

export function GetGitHubToken():Promise<string>;

export function GetGitHubUser(arg1:string):Promise<backup_svc.GitHubUser>;

export function GetGroup(arg1:number):Promise<group_entity.Group>;

export function GetLanguage():Promise<string>;

export function GetModelDefaults(arg1:string):Promise<app.AIModelInfo>;

export function GetOpsctlInstallDir():Promise<string>;

export function GetPluginReferenceDir():Promise<string>;

export function GetSSHPoolConnections():Promise<Array<sshpool.PoolEntryInfo>>;

export function GetSkillPreview():Promise<string>;

export function GetStoredGitHubUser():Promise<string>;

export function GetSystemStatus():Promise<Array<status.Entry>>;

export function GetUpdateChannel():Promise<string>;

export function ImportFromGist(arg1:string,arg2:string,arg3:string,arg4:backup_svc.ImportOptions):Promise<backup_svc.ImportResult>;

export function ImportSSHConfigSelected(arg1:Array<number>,arg2:boolean):Promise<import_svc.ImportResult>;

export function ImportSSHKeyFile(arg1:string,arg2:string):Promise<credential_entity.Credential>;

export function ImportSSHKeyPEM(arg1:string,arg2:string,arg3:string):Promise<credential_entity.Credential>;

export function ImportTabbySelected(arg1:Array<number>,arg2:string,arg3:boolean):Promise<import_svc.ImportResult>;

export function InitAIProvider():Promise<void>;

export function InstallExtension():Promise<extension_svc.ExtensionInfo>;

export function InstallExtensionFromDirectory():Promise<extension_svc.ExtensionInfo>;

export function InstallOpsctl(arg1:string):Promise<string>;

export function InstallSkills():Promise<void>;

export function ListAIProviders():Promise<Array<app.AIProviderInfo>>;

export function ListAssets(arg1:string,arg2:number):Promise<Array<asset_entity.Asset>>;

export function ListAuditLogs(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<app.AuditLogListResult>;

export function ListAuditSessions(arg1:number):Promise<Array<audit_repo.SessionInfo>>;

export function ListBackupGists(arg1:string):Promise<Array<backup_svc.GistInfo>>;

export function ListConversations():Promise<Array<conversation_entity.Conversation>>;

export function ListCredentials():Promise<Array<credential_entity.Credential>>;

export function ListCredentialsByType(arg1:string):Promise<Array<credential_entity.Credential>>;

export function ListForwardConfigs():Promise<Array<app.ForwardConfigWithStatus>>;

export function ListGroups():Promise<Array<group_entity.Group>>;

export function ListInstalledExtensions():Promise<Array<extension_svc.ExtensionInfo>>;

export function ListLocalSSHKeys():Promise<Array<app.LocalSSHKeyInfo>>;

export function ListPolicyGroups(arg1:string):Promise<Array<policy_group_entity.PolicyGroupItem>>;

export function MoveAsset(arg1:number,arg2:string):Promise<void>;

export function MoveGroup(arg1:number,arg2:string):Promise<void>;

export function OnSecondInstanceLaunch():Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function PreviewGistBackup(arg1:string,arg2:string,arg3:string):Promise<backup_svc.BackupSummary>;

export function PreviewImportFile(arg1:string,arg2:string):Promise<backup_svc.BackupSummary>;

export function PreviewSSHConfig():Promise<import_svc.PreviewResult>;

export function PreviewTabbyConfig():Promise<import_svc.PreviewResult>;

export function QueueAIMessage(arg1:number,arg2:string):Promise<void>;

export function ReloadExtensions():Promise<void>;

export function ResizeSSH(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondAIApproval(arg1:string,arg2:ai.ApprovalResponse):Promise<void>;

export function RespondAuthChallenge(arg1:string,arg2:Array<string>):Promise<void>;

export function RespondHostKeyVerify(arg1:string,arg2:number):Promise<void>;

export function RespondOpsctlApproval(arg1:string,arg2:ai.ApprovalResponse):Promise<void>;

export function RespondPermission(arg1:string,arg2:string):Promise<void>;

export function SFTPCancelTransfer(arg1:string):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string):Promise<string>;

export function SFTPDownloadDir(arg1:string,arg2:string):Promise<string>;

export function SFTPGetwd(arg1:string):Promise<string>;

export function SFTPListDir(arg1:string,arg2:string):Promise<Array<sftp_svc.FileEntry>>;

export function SFTPUpload(arg1:string,arg2:string):Promise<string>;

export function SFTPUploadDir(arg1:string,arg2:string):Promise<string>;

export function SFTPUploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveConversationMessages(arg1:number,arg2:Array<app.ConversationDisplayMessage>):Promise<void>;

export function SaveGitHubToken(arg1:string,arg2:string):Promise<void>;

export function SelectImportFile():Promise<app.ImportFileInfo>;

export function SelectSSHKeyFile():Promise<app.LocalSSHKeyInfo>;

export function SendAIMessage(arg1:number,arg2:Array<ai.Message>,arg3:ai.AIContext):Promise<void>;

export function SetActiveAIProvider(arg1:number):Promise<void>;

export function SetDownloadMirror(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetUpdateChannel(arg1:string):Promise<void>;

export function SplitSSH(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StartForwardConfig(arg1:number):Promise<void>;

export function StartGitHubDeviceFlow():Promise<backup_svc.DeviceFlowInfo>;

export function StopAIGeneration(arg1:number):Promise<void>;

export function StopForwardConfig(arg1:number):Promise<void>;

export function SwitchConversation(arg1:number):Promise<Array<app.ConversationDisplayMessage>>;

export function TestDatabaseConnection(arg1:string,arg2:string):Promise<void>;

export function TestPolicyRule(arg1:app.PolicyTestRequest):Promise<app.PolicyTestResult>;

export function TestRedisConnection(arg1:string,arg2:string):Promise<void>;

export function TestSSHConnection(arg1:string,arg2:string):Promise<void>;

export function UninstallExtension(arg1:string,arg2:boolean):Promise<void>;

export function UpdateAIProvider(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<void>;

export function UpdateAsset(arg1:asset_entity.Asset):Promise<void>;

export function UpdateAssetPassword(arg1:number,arg2:string):Promise<void>;

export function UpdateCredential(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<credential_entity.Credential>;

export function UpdateCredentialPassword(arg1:number,arg2:string):Promise<void>;

export function UpdateForwardConfig(arg1:number,arg2:string,arg3:number,arg4:Array<forward_entity.ForwardRule>):Promise<forward_entity.ForwardConfig>;

export function UpdateGroup(arg1:group_entity.Group):Promise<void>;

export function UpdatePolicyGroup(arg1:policy_group_entity.PolicyGroup):Promise<void>;

export function WaitGitHubDeviceAuth(arg1:string,arg2:number):Promise<string>;

export function WriteSSH(arg1:string,arg2:string):Promise<void>;
