// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallExtensionAction(arg1, arg2, arg3) {
  return window['go']['app']['App']['CallExtensionAction'](arg1, arg2, arg3);
}

export function CallExtensionTool(arg1, arg2, arg3) {
  return window['go']['app']['App']['CallExtensionTool'](arg1, arg2, arg3);
}

export function CancelGitHubAuth() {
  return window['go']['app']['App']['CancelGitHubAuth']();
}

export function CancelSSHConnect(arg1) {
  return window['go']['app']['App']['CancelSSHConnect'](arg1);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function Cleanup() {
  return window['go']['app']['App']['Cleanup']();
}

export function ClearGitHubToken() {
  return window['go']['app']['App']['ClearGitHubToken']();
}

export function ConnectSSH(arg1) {
  return window['go']['app']['App']['ConnectSSH'](arg1);
}

export function ConnectSSHAsync(arg1) {
  return window['go']['app']['App']['ConnectSSHAsync'](arg1);
}

export function CopyPolicyGroup(arg1, arg2) {
  return window['go']['app']['App']['CopyPolicyGroup'](arg1, arg2);
}

export function CreateAIProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['CreateAIProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateAsset(arg1) {
  return window['go']['app']['App']['CreateAsset'](arg1);
}

export function CreateConversation() {
  return window['go']['app']['App']['CreateConversation']();
}

export function CreateForwardConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateForwardConfig'](arg1, arg2, arg3);
}

export function CreateGroup(arg1) {
  return window['go']['app']['App']['CreateGroup'](arg1);
}

export function CreatePasswordCredential(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreatePasswordCredential'](arg1, arg2, arg3, arg4);
}

export function CreatePolicyGroup(arg1) {
  return window['go']['app']['App']['CreatePolicyGroup'](arg1);
}

export function DeleteAIProvider(arg1) {
  return window['go']['app']['App']['DeleteAIProvider'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['app']['App']['DeleteAsset'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['app']['App']['DeleteConversation'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['app']['App']['DeleteCredential'](arg1);
}

export function DeleteForwardConfig(arg1) {
  return window['go']['app']['App']['DeleteForwardConfig'](arg1);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['app']['App']['DeleteGroup'](arg1, arg2);
}

export function DeletePolicyGroup(arg1) {
  return window['go']['app']['App']['DeletePolicyGroup'](arg1);
}

export function DetectOpsctl() {
  return window['go']['app']['App']['DetectOpsctl']();
}

export function DetectSkills() {
  return window['go']['app']['App']['DetectSkills']();
}

export function DisableExtension(arg1) {
  return window['go']['app']['App']['DisableExtension'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['app']['App']['DisconnectSSH'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['app']['App']['DownloadAndInstallUpdate'](arg1);
}

export function EnableExtension(arg1) {
  return window['go']['app']['App']['EnableExtension'](arg1);
}

export function EncryptPassword(arg1) {
  return window['go']['app']['App']['EncryptPassword'](arg1);
}

export function ExecuteImportFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteImportFile'](arg1, arg2, arg3);
}

export function ExecuteRedis(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteRedis'](arg1, arg2, arg3);
}

export function ExecuteRedisArgs(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteRedisArgs'](arg1, arg2, arg3);
}

export function ExecuteSQL(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteSQL'](arg1, arg2, arg3);
}

export function ExportData() {
  return window['go']['app']['App']['ExportData']();
}

export function ExportToFile(arg1, arg2) {
  return window['go']['app']['App']['ExportToFile'](arg1, arg2);
}

export function ExportToGist(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportToGist'](arg1, arg2, arg3, arg4);
}

export function FetchAIModels(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchAIModels'](arg1, arg2, arg3);
}

export function GenerateSSHKey(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GenerateSSHKey'](arg1, arg2, arg3, arg4);
}

export function GetActiveAIProvider() {
  return window['go']['app']['App']['GetActiveAIProvider']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetAsset(arg1) {
  return window['go']['app']['App']['GetAsset'](arg1);
}

export function GetAssetPassword(arg1) {
  return window['go']['app']['App']['GetAssetPassword'](arg1);
}

export function GetAvailableAssetTypes() {
  return window['go']['app']['App']['GetAvailableAssetTypes']();
}

export function GetAvailableMirrors() {
  return window['go']['app']['App']['GetAvailableMirrors']();
}

export function GetCredentialPublicKey(arg1) {
  return window['go']['app']['App']['GetCredentialPublicKey'](arg1);
}

export function GetCredentialUsage(arg1) {
  return window['go']['app']['App']['GetCredentialUsage'](arg1);
}

export function GetCurrentConversationID() {
  return window['go']['app']['App']['GetCurrentConversationID']();
}

export function GetDataDir() {
  return window['go']['app']['App']['GetDataDir']();
}

export function GetDecryptedExtensionConfig(arg1, arg2) {
  return window['go']['app']['App']['GetDecryptedExtensionConfig'](arg1, arg2);
}

export function GetDefaultPolicy(arg1) {
  return window['go']['app']['App']['GetDefaultPolicy'](arg1);
}

export function GetDownloadMirror() {
  return window['go']['app']['App']['GetDownloadMirror']();
}

export function GetExtensionDetail(arg1) {
  return window['go']['app']['App']['GetExtensionDetail'](arg1);
}

export function GetExtensionManifest(arg1) {
  return window['go']['app']['App']['GetExtensionManifest'](arg1);
}

export function GetGitHubToken() {
  return window['go']['app']['App']['GetGitHubToken']();
}

export function GetGitHubUser(arg1) {
  return window['go']['app']['App']['GetGitHubUser'](arg1);
}

export function GetGroup(arg1) {
  return window['go']['app']['App']['GetGroup'](arg1);
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetModelDefaults(arg1) {
  return window['go']['app']['App']['GetModelDefaults'](arg1);
}

export function GetOpsctlInstallDir() {
  return window['go']['app']['App']['GetOpsctlInstallDir']();
}

export function GetPluginReferenceDir() {
  return window['go']['app']['App']['GetPluginReferenceDir']();
}

export function GetSSHPoolConnections() {
  return window['go']['app']['App']['GetSSHPoolConnections']();
}

export function GetSkillPreview() {
  return window['go']['app']['App']['GetSkillPreview']();
}

export function GetStoredGitHubUser() {
  return window['go']['app']['App']['GetStoredGitHubUser']();
}

export function GetSystemStatus() {
  return window['go']['app']['App']['GetSystemStatus']();
}

export function GetUpdateChannel() {
  return window['go']['app']['App']['GetUpdateChannel']();
}

export function ImportFromGist(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportFromGist'](arg1, arg2, arg3, arg4);
}

export function ImportSSHConfigSelected(arg1, arg2) {
  return window['go']['app']['App']['ImportSSHConfigSelected'](arg1, arg2);
}

export function ImportSSHKeyFile(arg1, arg2) {
  return window['go']['app']['App']['ImportSSHKeyFile'](arg1, arg2);
}

export function ImportSSHKeyPEM(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportSSHKeyPEM'](arg1, arg2, arg3);
}

export function ImportTabbySelected(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportTabbySelected'](arg1, arg2, arg3);
}

export function InitAIProvider() {
  return window['go']['app']['App']['InitAIProvider']();
}

export function InstallExtension() {
  return window['go']['app']['App']['InstallExtension']();
}

export function InstallExtensionFromDirectory() {
  return window['go']['app']['App']['InstallExtensionFromDirectory']();
}

export function InstallOpsctl(arg1) {
  return window['go']['app']['App']['InstallOpsctl'](arg1);
}

export function InstallSkills() {
  return window['go']['app']['App']['InstallSkills']();
}

export function ListAIProviders() {
  return window['go']['app']['App']['ListAIProviders']();
}

export function ListAssets(arg1, arg2) {
  return window['go']['app']['App']['ListAssets'](arg1, arg2);
}

export function ListAuditLogs(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['ListAuditLogs'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListAuditSessions(arg1) {
  return window['go']['app']['App']['ListAuditSessions'](arg1);
}

export function ListBackupGists(arg1) {
  return window['go']['app']['App']['ListBackupGists'](arg1);
}

export function ListConversations() {
  return window['go']['app']['App']['ListConversations']();
}

export function ListCredentials() {
  return window['go']['app']['App']['ListCredentials']();
}

export function ListCredentialsByType(arg1) {
  return window['go']['app']['App']['ListCredentialsByType'](arg1);
}

export function ListForwardConfigs() {
  return window['go']['app']['App']['ListForwardConfigs']();
}

export function ListGroups() {
  return window['go']['app']['App']['ListGroups']();
}

export function ListInstalledExtensions() {
  return window['go']['app']['App']['ListInstalledExtensions']();
}

export function ListLocalSSHKeys() {
  return window['go']['app']['App']['ListLocalSSHKeys']();
}

export function ListPolicyGroups(arg1) {
  return window['go']['app']['App']['ListPolicyGroups'](arg1);
}

export function MoveAsset(arg1, arg2) {
  return window['go']['app']['App']['MoveAsset'](arg1, arg2);
}

export function MoveGroup(arg1, arg2) {
  return window['go']['app']['App']['MoveGroup'](arg1, arg2);
}

export function OnSecondInstanceLaunch() {
  return window['go']['app']['App']['OnSecondInstanceLaunch']();
}

export function OpenDirectory(arg1) {
  return window['go']['app']['App']['OpenDirectory'](arg1);
}

export function PreviewGistBackup(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewGistBackup'](arg1, arg2, arg3);
}

export function PreviewImportFile(arg1, arg2) {
  return window['go']['app']['App']['PreviewImportFile'](arg1, arg2);
}

export function PreviewSSHConfig() {
  return window['go']['app']['App']['PreviewSSHConfig']();
}

export function PreviewTabbyConfig() {
  return window['go']['app']['App']['PreviewTabbyConfig']();
}

export function QueueAIMessage(arg1, arg2) {
  return window['go']['app']['App']['QueueAIMessage'](arg1, arg2);
}

export function ReloadExtensions() {
  return window['go']['app']['App']['ReloadExtensions']();
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function RespondAIApproval(arg1, arg2) {
  return window['go']['app']['App']['RespondAIApproval'](arg1, arg2);
}

export function RespondAuthChallenge(arg1, arg2) {
  return window['go']['app']['App']['RespondAuthChallenge'](arg1, arg2);
}

export function RespondHostKeyVerify(arg1, arg2) {
  return window['go']['app']['App']['RespondHostKeyVerify'](arg1, arg2);
}

export function RespondOpsctlApproval(arg1, arg2) {
  return window['go']['app']['App']['RespondOpsctlApproval'](arg1, arg2);
}

export function RespondPermission(arg1, arg2) {
  return window['go']['app']['App']['RespondPermission'](arg1, arg2);
}

export function SFTPCancelTransfer(arg1) {
  return window['go']['app']['App']['SFTPCancelTransfer'](arg1);
}

export function SFTPDelete(arg1, arg2, arg3) {
  return window['go']['app']['App']['SFTPDelete'](arg1, arg2, arg3);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['app']['App']['SFTPDownload'](arg1, arg2);
}

export function SFTPDownloadDir(arg1, arg2) {
  return window['go']['app']['App']['SFTPDownloadDir'](arg1, arg2);
}

export function SFTPGetwd(arg1) {
  return window['go']['app']['App']['SFTPGetwd'](arg1);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['app']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPUpload(arg1, arg2) {
  return window['go']['app']['App']['SFTPUpload'](arg1, arg2);
}

export function SFTPUploadDir(arg1, arg2) {
  return window['go']['app']['App']['SFTPUploadDir'](arg1, arg2);
}

export function SFTPUploadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SFTPUploadFile'](arg1, arg2, arg3);
}

export function SaveConversationMessages(arg1, arg2) {
  return window['go']['app']['App']['SaveConversationMessages'](arg1, arg2);
}

export function SaveGitHubToken(arg1, arg2) {
  return window['go']['app']['App']['SaveGitHubToken'](arg1, arg2);
}

export function SelectImportFile() {
  return window['go']['app']['App']['SelectImportFile']();
}

export function SelectSSHKeyFile() {
  return window['go']['app']['App']['SelectSSHKeyFile']();
}

export function SendAIMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendAIMessage'](arg1, arg2, arg3);
}

export function SetActiveAIProvider(arg1) {
  return window['go']['app']['App']['SetActiveAIProvider'](arg1);
}

export function SetDownloadMirror(arg1) {
  return window['go']['app']['App']['SetDownloadMirror'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetUpdateChannel(arg1) {
  return window['go']['app']['App']['SetUpdateChannel'](arg1);
}

export function SplitSSH(arg1, arg2, arg3) {
  return window['go']['app']['App']['SplitSSH'](arg1, arg2, arg3);
}

export function StartForwardConfig(arg1) {
  return window['go']['app']['App']['StartForwardConfig'](arg1);
}

export function StartGitHubDeviceFlow() {
  return window['go']['app']['App']['StartGitHubDeviceFlow']();
}

export function StopAIGeneration(arg1) {
  return window['go']['app']['App']['StopAIGeneration'](arg1);
}

export function StopForwardConfig(arg1) {
  return window['go']['app']['App']['StopForwardConfig'](arg1);
}

export function SwitchConversation(arg1) {
  return window['go']['app']['App']['SwitchConversation'](arg1);
}

export function TestDatabaseConnection(arg1, arg2) {
  return window['go']['app']['App']['TestDatabaseConnection'](arg1, arg2);
}

export function TestPolicyRule(arg1) {
  return window['go']['app']['App']['TestPolicyRule'](arg1);
}

export function TestRedisConnection(arg1, arg2) {
  return window['go']['app']['App']['TestRedisConnection'](arg1, arg2);
}

export function TestSSHConnection(arg1, arg2) {
  return window['go']['app']['App']['TestSSHConnection'](arg1, arg2);
}

export function UninstallExtension(arg1, arg2) {
  return window['go']['app']['App']['UninstallExtension'](arg1, arg2);
}

export function UpdateAIProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['UpdateAIProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateAsset(arg1) {
  return window['go']['app']['App']['UpdateAsset'](arg1);
}

export function UpdateAssetPassword(arg1, arg2) {
  return window['go']['app']['App']['UpdateAssetPassword'](arg1, arg2);
}

export function UpdateCredential(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateCredential'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCredentialPassword(arg1, arg2) {
  return window['go']['app']['App']['UpdateCredentialPassword'](arg1, arg2);
}

export function UpdateForwardConfig(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateForwardConfig'](arg1, arg2, arg3, arg4);
}

export function UpdateGroup(arg1) {
  return window['go']['app']['App']['UpdateGroup'](arg1);
}

export function UpdatePolicyGroup(arg1) {
  return window['go']['app']['App']['UpdatePolicyGroup'](arg1);
}

export function WaitGitHubDeviceAuth(arg1, arg2) {
  return window['go']['app']['App']['WaitGitHubDeviceAuth'](arg1, arg2);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['app']['App']['WriteSSH'](arg1, arg2);
}
