// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGitHubAuth() {
  return window['go']['main']['App']['CancelGitHubAuth']();
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function CreateAsset(arg1) {
  return window['go']['main']['App']['CreateAsset'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['main']['App']['DeleteGroup'](arg1, arg2);
}

export function DeleteSSHKey(arg1) {
  return window['go']['main']['App']['DeleteSSHKey'](arg1);
}

export function DetectLocalCLIs() {
  return window['go']['main']['App']['DetectLocalCLIs']();
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function ExecuteImportFile(arg1, arg2) {
  return window['go']['main']['App']['ExecuteImportFile'](arg1, arg2);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function ExportToFile(arg1) {
  return window['go']['main']['App']['ExportToFile'](arg1);
}

export function ExportToGist(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToGist'](arg1, arg2, arg3);
}

export function GenerateSSHKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateSSHKey'](arg1, arg2, arg3, arg4);
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetGitHubUser(arg1) {
  return window['go']['main']['App']['GetGitHubUser'](arg1);
}

export function GetInitContext(arg1, arg2) {
  return window['go']['main']['App']['GetInitContext'](arg1, arg2);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetSSHKeyPublicKey(arg1) {
  return window['go']['main']['App']['GetSSHKeyPublicKey'](arg1);
}

export function GetSSHKeyUsage(arg1) {
  return window['go']['main']['App']['GetSSHKeyUsage'](arg1);
}

export function ImportFromGist(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportFromGist'](arg1, arg2, arg3);
}

export function ImportSSHKeyFile(arg1, arg2) {
  return window['go']['main']['App']['ImportSSHKeyFile'](arg1, arg2);
}

export function ImportSSHKeyPEM(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportSSHKeyPEM'](arg1, arg2, arg3);
}

export function ImportTabbySelected(arg1) {
  return window['go']['main']['App']['ImportTabbySelected'](arg1);
}

export function ListAssets(arg1, arg2) {
  return window['go']['main']['App']['ListAssets'](arg1, arg2);
}

export function ListBackupGists(arg1) {
  return window['go']['main']['App']['ListBackupGists'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListLocalSSHKeys() {
  return window['go']['main']['App']['ListLocalSSHKeys']();
}

export function ListSSHKeys() {
  return window['go']['main']['App']['ListSSHKeys']();
}

export function LoadCredential(arg1) {
  return window['go']['main']['App']['LoadCredential'](arg1);
}

export function PreviewTabbyConfig() {
  return window['go']['main']['App']['PreviewTabbyConfig']();
}

export function ResetAISession() {
  return window['go']['main']['App']['ResetAISession']();
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function SFTPCancelTransfer(arg1) {
  return window['go']['main']['App']['SFTPCancelTransfer'](arg1);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2);
}

export function SFTPDownloadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownloadDir'](arg1, arg2);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPUpload(arg1, arg2) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2);
}

export function SFTPUploadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPUploadDir'](arg1, arg2);
}

export function SaveCredential(arg1) {
  return window['go']['main']['App']['SaveCredential'](arg1);
}

export function SelectImportFile() {
  return window['go']['main']['App']['SelectImportFile']();
}

export function SelectSSHKeyFile() {
  return window['go']['main']['App']['SelectSSHKeyFile']();
}

export function SendAIMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAIMessage'](arg1, arg2);
}

export function SetAIProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAIProvider'](arg1, arg2, arg3, arg4);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StartGitHubDeviceFlow() {
  return window['go']['main']['App']['StartGitHubDeviceFlow']();
}

export function UpdateAsset(arg1) {
  return window['go']['main']['App']['UpdateAsset'](arg1);
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function UpdateSSHKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSSHKey'](arg1, arg2, arg3);
}

export function WaitGitHubDeviceAuth(arg1, arg2) {
  return window['go']['main']['App']['WaitGitHubDeviceAuth'](arg1, arg2);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['main']['App']['WriteSSH'](arg1, arg2);
}
