// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGitHubAuth() {
  return window['go']['main']['App']['CancelGitHubAuth']();
}

export function CancelSSHConnect(arg1) {
  return window['go']['main']['App']['CancelSSHConnect'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearGitHubToken() {
  return window['go']['main']['App']['ClearGitHubToken']();
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function ConnectSSHAsync(arg1) {
  return window['go']['main']['App']['ConnectSSHAsync'](arg1);
}

export function CopyPolicyGroup(arg1, arg2) {
  return window['go']['main']['App']['CopyPolicyGroup'](arg1, arg2);
}

export function CreateAsset(arg1) {
  return window['go']['main']['App']['CreateAsset'](arg1);
}

export function CreateConversation() {
  return window['go']['main']['App']['CreateConversation']();
}

export function CreateForwardConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateForwardConfig'](arg1, arg2, arg3);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreatePasswordCredential(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePasswordCredential'](arg1, arg2, arg3, arg4);
}

export function CreatePolicyGroup(arg1) {
  return window['go']['main']['App']['CreatePolicyGroup'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function DeleteForwardConfig(arg1) {
  return window['go']['main']['App']['DeleteForwardConfig'](arg1);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['main']['App']['DeleteGroup'](arg1, arg2);
}

export function DeletePolicyGroup(arg1) {
  return window['go']['main']['App']['DeletePolicyGroup'](arg1);
}

export function DetectLocalCLIs() {
  return window['go']['main']['App']['DetectLocalCLIs']();
}

export function DetectOpsctl() {
  return window['go']['main']['App']['DetectOpsctl']();
}

export function DetectSkills() {
  return window['go']['main']['App']['DetectSkills']();
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['App']['DownloadAndInstallUpdate']();
}

export function EncryptPassword(arg1) {
  return window['go']['main']['App']['EncryptPassword'](arg1);
}

export function ExecuteImportFile(arg1, arg2) {
  return window['go']['main']['App']['ExecuteImportFile'](arg1, arg2);
}

export function ExecuteRedis(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteRedis'](arg1, arg2, arg3);
}

export function ExecuteRedisArgs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteRedisArgs'](arg1, arg2, arg3);
}

export function ExecuteSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSQL'](arg1, arg2, arg3);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function ExportToFile(arg1) {
  return window['go']['main']['App']['ExportToFile'](arg1);
}

export function ExportToGist(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToGist'](arg1, arg2, arg3);
}

export function GenerateSSHKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateSSHKey'](arg1, arg2, arg3, arg4);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetCredentialPublicKey(arg1) {
  return window['go']['main']['App']['GetCredentialPublicKey'](arg1);
}

export function GetCredentialUsage(arg1) {
  return window['go']['main']['App']['GetCredentialUsage'](arg1);
}

export function GetCurrentConversationID() {
  return window['go']['main']['App']['GetCurrentConversationID']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDefaultPolicy(arg1) {
  return window['go']['main']['App']['GetDefaultPolicy'](arg1);
}

export function GetGitHubToken() {
  return window['go']['main']['App']['GetGitHubToken']();
}

export function GetGitHubUser(arg1) {
  return window['go']['main']['App']['GetGitHubUser'](arg1);
}

export function GetGroup(arg1) {
  return window['go']['main']['App']['GetGroup'](arg1);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetOpsctlInstallDir() {
  return window['go']['main']['App']['GetOpsctlInstallDir']();
}

export function GetSSHPoolConnections() {
  return window['go']['main']['App']['GetSSHPoolConnections']();
}

export function GetSkillPreview() {
  return window['go']['main']['App']['GetSkillPreview']();
}

export function GetStoredGitHubUser() {
  return window['go']['main']['App']['GetStoredGitHubUser']();
}

export function GetUpdateChannel() {
  return window['go']['main']['App']['GetUpdateChannel']();
}

export function ImportFromGist(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportFromGist'](arg1, arg2, arg3);
}

export function ImportSSHConfigSelected(arg1, arg2) {
  return window['go']['main']['App']['ImportSSHConfigSelected'](arg1, arg2);
}

export function ImportSSHKeyFile(arg1, arg2) {
  return window['go']['main']['App']['ImportSSHKeyFile'](arg1, arg2);
}

export function ImportSSHKeyPEM(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportSSHKeyPEM'](arg1, arg2, arg3);
}

export function ImportTabbySelected(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportTabbySelected'](arg1, arg2, arg3);
}

export function InstallOpsctl(arg1) {
  return window['go']['main']['App']['InstallOpsctl'](arg1);
}

export function InstallSkills() {
  return window['go']['main']['App']['InstallSkills']();
}

export function ListAssets(arg1, arg2) {
  return window['go']['main']['App']['ListAssets'](arg1, arg2);
}

export function ListAuditLogs(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ListAuditLogs'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListAuditSessions(arg1) {
  return window['go']['main']['App']['ListAuditSessions'](arg1);
}

export function ListBackupGists(arg1) {
  return window['go']['main']['App']['ListBackupGists'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function ListCredentialsByType(arg1) {
  return window['go']['main']['App']['ListCredentialsByType'](arg1);
}

export function ListForwardConfigs() {
  return window['go']['main']['App']['ListForwardConfigs']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListLocalSSHKeys() {
  return window['go']['main']['App']['ListLocalSSHKeys']();
}

export function ListPolicyGroups(arg1) {
  return window['go']['main']['App']['ListPolicyGroups'](arg1);
}

export function LoadAISetting() {
  return window['go']['main']['App']['LoadAISetting']();
}

export function MoveAsset(arg1, arg2) {
  return window['go']['main']['App']['MoveAsset'](arg1, arg2);
}

export function MoveGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveGroup'](arg1, arg2);
}

export function PreviewSSHConfig() {
  return window['go']['main']['App']['PreviewSSHConfig']();
}

export function PreviewTabbyConfig() {
  return window['go']['main']['App']['PreviewTabbyConfig']();
}

export function ResetAISession() {
  return window['go']['main']['App']['ResetAISession']();
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function RespondAuthChallenge(arg1, arg2) {
  return window['go']['main']['App']['RespondAuthChallenge'](arg1, arg2);
}

export function RespondCommandConfirm(arg1, arg2) {
  return window['go']['main']['App']['RespondCommandConfirm'](arg1, arg2);
}

export function RespondOpsctlApproval(arg1, arg2) {
  return window['go']['main']['App']['RespondOpsctlApproval'](arg1, arg2);
}

export function RespondOpsctlApprovalSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RespondOpsctlApprovalSession'](arg1, arg2, arg3, arg4, arg5);
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function RespondPlanApproval(arg1, arg2) {
  return window['go']['main']['App']['RespondPlanApproval'](arg1, arg2);
}

export function RespondPlanApprovalWithEdits(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondPlanApprovalWithEdits'](arg1, arg2, arg3);
}

export function SFTPCancelTransfer(arg1) {
  return window['go']['main']['App']['SFTPCancelTransfer'](arg1);
}

export function SFTPDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2, arg3);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2);
}

export function SFTPDownloadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownloadDir'](arg1, arg2);
}

export function SFTPGetwd(arg1) {
  return window['go']['main']['App']['SFTPGetwd'](arg1);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPUpload(arg1, arg2) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2);
}

export function SFTPUploadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPUploadDir'](arg1, arg2);
}

export function SFTPUploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUploadFile'](arg1, arg2, arg3);
}

export function SaveAISetting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAISetting'](arg1, arg2, arg3, arg4);
}

export function SaveConversationMessages(arg1, arg2) {
  return window['go']['main']['App']['SaveConversationMessages'](arg1, arg2);
}

export function SaveGitHubToken(arg1, arg2) {
  return window['go']['main']['App']['SaveGitHubToken'](arg1, arg2);
}

export function SelectImportFile() {
  return window['go']['main']['App']['SelectImportFile']();
}

export function SelectSSHKeyFile() {
  return window['go']['main']['App']['SelectSSHKeyFile']();
}

export function SendAIMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAIMessage'](arg1, arg2);
}

export function SetAIProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAIProvider'](arg1, arg2, arg3, arg4);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetUpdateChannel(arg1) {
  return window['go']['main']['App']['SetUpdateChannel'](arg1);
}

export function SplitSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitSSH'](arg1, arg2, arg3);
}

export function StartForwardConfig(arg1) {
  return window['go']['main']['App']['StartForwardConfig'](arg1);
}

export function StartGitHubDeviceFlow() {
  return window['go']['main']['App']['StartGitHubDeviceFlow']();
}

export function StopForwardConfig(arg1) {
  return window['go']['main']['App']['StopForwardConfig'](arg1);
}

export function SwitchConversation(arg1) {
  return window['go']['main']['App']['SwitchConversation'](arg1);
}

export function TestDatabaseConnection(arg1, arg2) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1, arg2);
}

export function TestPolicyRule(arg1) {
  return window['go']['main']['App']['TestPolicyRule'](arg1);
}

export function TestRedisConnection(arg1, arg2) {
  return window['go']['main']['App']['TestRedisConnection'](arg1, arg2);
}

export function TestSSHConnection(arg1, arg2) {
  return window['go']['main']['App']['TestSSHConnection'](arg1, arg2);
}

export function UpdateAsset(arg1) {
  return window['go']['main']['App']['UpdateAsset'](arg1);
}

export function UpdateAssetPassword(arg1, arg2) {
  return window['go']['main']['App']['UpdateAssetPassword'](arg1, arg2);
}

export function UpdateCredential(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCredential'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCredentialPassword(arg1, arg2) {
  return window['go']['main']['App']['UpdateCredentialPassword'](arg1, arg2);
}

export function UpdateForwardConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateForwardConfig'](arg1, arg2, arg3, arg4);
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function UpdatePolicyGroup(arg1) {
  return window['go']['main']['App']['UpdatePolicyGroup'](arg1);
}

export function WaitGitHubDeviceAuth(arg1, arg2) {
  return window['go']['main']['App']['WaitGitHubDeviceAuth'](arg1, arg2);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['main']['App']['WriteSSH'](arg1, arg2);
}
